require "rails"
require "rails/generators"
require "rails/generators/model_generator"
require "rails/generators/resource_generator"

require "spinaltap/version"
require "spinaltap/engine"
require "spinaltap/generators/generator_helpers"
require "spinaltap/generators/named_generator_helpers"
require "spinaltap/generators/install/install_generator"
require "spinaltap/generators/model/model_generator"
require "spinaltap/generators/collection/collection_generator"
require "spinaltap/generators/view/view_generator"
require "spinaltap/generators/template/template_generator"
require "spinaltap/generators/helper/helper_generator"