require "rails"
require "rails/generators/model_generator"

require "vertebrae/version"
require "vertebrae/engine"
require "vertebrae/generators/generator_helpers"
require "vertebrae/generators/named_generator_helpers"
require "vertebrae/generators/install/install_generator"
require "vertebrae/generators/model/model_generator"
require "vertebrae/generators/collection/collection_generator"